### ISSUE TITLE
Configurable reconnect timer

### ISSUE THREAD

**Issue by madhatr** [carlbennett/BNRBot#17]
As it stands 5 minutes is the only option.  I found the 300000ms setting and could have forked it to change something I think(not really sure about the whole fork thing) but I though it would be better if it were added to the configuration screen.   I don't know anything about realBASIC and its forms so I would be lost there.

**Comment by carlbennett** [comment]
I don't know much about the .rbvcp format myself. I just use the Realbasic IDE and let git handle the changes. (I'm actually pretty concerned about how much git likes a change to the .rbuistate **binary** file every commit, but that's another story.) Point is the forms are really called windows, and the windows are very easy to change in the IDE.

I'll see about adding this in a later build.

**Comment by carlbennett** [comment]
Resolved in 8615b5d7ad846d1b01e89f7a21b829e8e11cd358.
